### ISSUE TITLE
Missing library modules?

### ISSUE THREAD

**Issue by gs20060101** [andreynovikov/maptrek#18]
Hi there,
I'm trying to build your app, but gradle stops with error message "Cannot evaluate module colorpicker : Configuration with name 'default' not found." I looked into libraries directory and found that those two directories, colorpicker and geo-coordinate-conversion, are empty. Am I supposed to download those libraries from somewhere?
Thanks for your help.

**Comment by andreynovikov** [comment]
My source files are a mess now. Have not commit all of them. Will fix it closer to release date.

**Comment by rzymek** [comment]
Also trying to build it, but still after clean clone and fetching submodules I'm getting:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module colorpicker : Configuration with name 'default' not found.


```

**Comment by andreynovikov** [comment]
I have updated all dependencies, now it should build. See instructions at the bottom of readme.
