### ISSUE TITLE
Latest Alpha (4) generates parse error

### ISSUE THREAD

**Issue by TuningGuide** [andreynovikov/maptrek#21]
fyi: after opening the MapTrek-alpha4.apk with paket installer it shows a parse error.

Regards

**Comment by andreynovikov** [comment]
It looks like your download was broken. Nevertheless I've just uploaded first beta.

**Comment by TuningGuide** [comment]
Strange, just downloaded beta apk to smartphone and laptop, checked md5 hashes but it still won't install. But nevermind I use Locus for now. Just wanted to let you know.
