### ISSUE TITLE
Help Wanted : how to update gradle files + compile with Android Studio 2.3.3

### ISSUE THREAD

**Issue by m20i02m** [andreynovikov/maptrek#46]
Hello
I don't succeed to compile the project and get the APK either with Android Studio 2.3.3 and Android Studio 1.5.1 so i need help from the project contributors.

I have limited skills on gradle settings, i made several attempts to edit those files but none of my attempts succeeded.
So i guess it's the place where i do some mistakes and that causes compilation to abort.
For example the 'app/build.gradle' files fails for the following: 

  compile project(':libraries:colorpicker')
  compile project(':libraries:geo-coordinate-conversion')

I also don't know how to make the following to compile for the Sector.java source file 
package gov.nasa.worldwind.geom;
Then i have an error showing that "java.awt.geom.Rectangle2D" is not found

Any help is welcome !
For example, can you set up the project to work with Android studio 2.3.3 and publish all the proper files and folders including the .idea folder

**Comment by martijn-heil** [comment]
I tried this recently too. After fixing several things myself, I concluded that there also was an entire java class missing from the repo! Namely, `mobi.maptrek.util.Geo`. This class is only used in `mobi.maptrek.data.Route`. I think the author doesn't have all of his files committed currently.

**Comment by andreynovikov** [comment]
I have updated all dependencies, now it should build. See instructions at the bottom of readme.
